-- 코드를 입력하세요
SELECT r.FOOD_TYPE, REST_ID, REST_NAME, fav AS FAVORITES
FROM REST_INFO r JOIN
(SELECT FOOD_TYPE, MAX(FAVORITES) AS fav
FROM REST_INFO
GROUP BY FOOD_TYPE) f
ON r.FOOD_TYPE = f.FOOD_TYPE AND r.FAVORITES = f.fav
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;