-- 코드를 작성해주세요
# SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
# FROM ITEM_INFO AS II LEFT JOIN ITEM_TREE AS IT
# ON II.ITEM_ID = IT.PARENT_ITEM_ID AND II.RARITY = 'RARE'
# ORDER BY II.ITEM_ID DESC;
SELECT TEMP.ITEM_ID, II2.ITEM_NAME, RARITY
FROM (SELECT IT.ITEM_ID
     FROM ITEM_INFO AS II
     LEFT JOIN ITEM_TREE AS IT
     ON II.ITEM_ID = IT.PARENT_ITEM_ID
     WHERE II.RARITY = 'RARE' AND IT.ITEM_ID IS NOT NULL) 
     AS TEMP 
     LEFT JOIN ITEM_INFO AS II2 
     ON TEMP.ITEM_ID = II2.ITEM_ID
ORDER BY 1 DESC;