-- 코드를 작성해주세요
SELECT CED.ID AS ID, CED.GENOTYPE AS GENOTYPE, PED.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS PED
JOIN ECOLI_DATA AS CED
ON PED.ID = CED.PARENT_ID
WHERE PED.GENOTYPE & CED.GENOTYPE = PED.GENOTYPE
ORDER BY CED.ID;